import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Search,Stethoscope,BookOpen,AlertTriangle,Plus,Trash2,Printer,FileText,ShieldCheck,Activity,ChevronRight}from'lucide-react';
import'./styles.css';

const SOURCES=[
 {id:'ICMR',title:'ICMR Standard Treatment Workflows of India',year:'2024',url:'https://www.icmr.gov.in/standard-treatment-workflows-stws',type:'India · Primary'},
 {id:'NCDC',title:'National Treatment Guidelines for Antimicrobial Use',year:'National portal',url:'https://ncdc.mohfw.gov.in/uploads/pdf/amr17.pdf',type:'India · Antimicrobial'},
 {id:'DENGUE',title:'National Guidelines for Clinical Management of Dengue',year:'MoHFW',url:'https://clinicalestablishments.mohfw.gov.in/en/standard-treatment-guidelines',type:'India · Dengue'},
 {id:'NTEP',title:'National Tuberculosis Elimination Programme',year:'Current portal',url:'https://tbcindia.mohfw.gov.in/guidelines/',type:'India · TB'},
 {id:'ESC',title:'ESC Chronic Coronary Syndromes Guideline',year:'2024',url:'https://www.escardio.org/Guidelines/Clinical-Practice-Guidelines/Chronic-Coronary-Syndromes',type:'International · Cardiology'},
 {id:'GOLD',title:'Global Strategy for COPD',year:'2026',url:'https://goldcopd.org/2026-gold-report-and-pocket-guide/',type:'International · Respiratory'},
 {id:'WHO',title:'WHO Dengue and Severe Dengue',year:'2025',url:'https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue',type:'International · Dengue'}
];
const M=(n,d,t,c)=>[n,d,t,c],C=(id,name,group,level,summary,red,tests,src,meds)=>({id,name,group,level,summary,red,tests,src,meds});
const CONDITIONS=[
C('htn','Hypertension','Cardiometabolic','Primary','Confirm with repeated office or out-of-office readings; assess CV risk and target-organ damage.',['BP ≥180/120 with acute organ injury → emergency care','Pregnancy, AKI, hyperkalaemia or suspected secondary hypertension → specialist pathway'],['Repeat BP / HBPM or ABPM','Creatinine/eGFR, Na/K, urine ACR','HbA1c/glucose, lipids, ECG'],['ICMR'],[M('Telmisartan','20–40 mg once daily','Long term','Avoid in pregnancy; monitor K+/creatinine'),M('Amlodipine','2.5–5 mg once daily','Long term','Edema; titrate by response'),M('Chlorthalidone','6.25–12.5 mg once daily','Long term','Monitor Na/K and uric acid'),M('Spironolactone','12.5–25 mg once daily','Resistant HTN only','Confirm resistance; monitor K+/renal function')]),
C('dm','Type 2 diabetes','Cardiometabolic','Primary','Individualize HbA1c goal; prioritize cardiorenal benefit in ASCVD, heart failure or CKD.',['DKA/HHS features, severe dehydration or altered sensorium → hospital','Pregnancy or suspected type 1 diabetes → specialist'],['HbA1c and glucose profile','eGFR and urine ACR','Lipids, BP, feet and retinal screening'],['ICMR'],[M('Metformin','500 mg with meal; titrate','Long term','Use by eGFR and GI tolerance'),M('Dapagliflozin','10 mg once daily','Long term','Sick-day rules; genital infection/DKA counselling'),M('Glimepiride','0.5–1 mg with breakfast','Review 2–4 weeks','Hypoglycaemia caution'),M('Basal insulin','Start/titrate per fasting glucose protocol','Individualized','Document device, units and hypoglycaemia plan')]),
C('angina','Stable angina / chronic coronary syndrome','Cardiology','Secondary','Use antianginal therapy plus event prevention after diagnostic and bleeding-risk review.',['Rest pain, dynamic ECG change, troponin rise or instability → ACS pathway','No outpatient template for suspected unstable angina'],['12-lead ECG','CBC, renal/liver function, HbA1c, lipids','Echo; ischemia/anatomy testing as appropriate'],['ICMR','ESC'],[M('Aspirin','75–100 mg once daily','Long term if indicated','Confirm indication/bleeding risk'),M('High-intensity statin','e.g. rosuvastatin 20 mg nightly','Long term','Set LDL-C goal'),M('Bisoprolol','2.5 mg once daily','Titrate','Check HR/BP/conduction/asthma'),M('Amlodipine','5 mg once daily','Titrate','Antianginal/BP option'),M('Nitroglycerin SL','0.4–0.5 mg as needed','Rescue','No PDE5 inhibitor; emergency plan'),M('Ranolazine','500 mg twice daily','Review 2–4 weeks','QT and interaction review')]),
C('pci','CAD after angioplasty / PCI','Cardiology','Secondary','Antiplatelet duration depends on ACS/elective PCI, stent, bleeding risk and anticoagulation.',['Recurrent chest pain, bleeding, syncope or acute dyspnoea → urgent assessment','Never stop DAPT without treating cardiology team review'],['CBC/bleeding review','Renal/liver function','Lipids and adherence'],['ICMR','ESC'],[M('Aspirin','75–100 mg once daily','Per PCI plan','Bleeding risk'),M('Clopidogrel','75 mg once daily','Per PCI plan','P2Y12 choice depends on context'),M('Ticagrelor','90 mg twice daily','ACS-specific plan','Dyspnoea, bleeding, interactions'),M('High-intensity statin','Rosuvastatin 20–40 mg','Long term','LDL-C goal'),M('Bisoprolol','1.25–5 mg daily','As indicated','HR/BP/LV function'),M('Telmisartan','20–40 mg daily','As indicated','BP/renal/K+')]),
C('hf','Heart failure with reduced EF','Cardiology','Secondary','Four foundational therapies where tolerated; diuretic dose follows congestion.',['Shock, hypoxia, confusion, rest dyspnoea or rapid edema → hospital','Check BP, renal function and K+ before RAAS/MRA titration'],['ECG, CXR, echo','CBC, renal/liver/thyroid, electrolytes','NT-proBNP where useful'],['ICMR'],[M('Sacubitril/valsartan','24/26 mg twice daily','Titrate 2–4 weekly','36-hour ACEI washout'),M('Bisoprolol','1.25 mg once daily','Slow titration','Start clinically stable/euvolemic'),M('Dapagliflozin','10 mg once daily','Long term','Sick-day guidance'),M('Eplerenone','25 mg once daily','Titrate','K+/eGFR thresholds'),M('Torsemide','5–20 mg once daily','By congestion','Weight/electrolyte plan')]),
C('af','Atrial fibrillation','Cardiology','Secondary','Confirm ECG; assess stroke risk, bleeding risk, symptoms and reversible triggers.',['Instability, ischemia, pulmonary edema or pre-excitation → emergency','DOAC dose requires age, weight, renal function and indication'],['12-lead ECG','CBC, creatinine/eGFR, LFT, TSH','Echo; CHA₂DS₂-VASc and bleeding review'],['ICMR'],[M('Apixaban','5 mg twice daily; reduce only if criteria met','Long term if indicated','Renal/age/weight/interaction check'),M('Bisoprolol','1.25–5 mg once daily','Titrate','Avoid excessive bradycardia'),M('Diltiazem','Individualized','Rate control','Avoid in HFrEF')]),
C('uri','Acute upper respiratory infection','Infectious disease','Primary','Most uncomplicated URIs are viral; use symptomatic care and safety-netting.',['Hypoxia, stridor, dehydration, sepsis or pneumonia signs → escalate','Antibiotics are not routine for uncomplicated viral URI'],['Usually none','Targeted testing during outbreaks/high-risk illness'],['ICMR','NCDC'],[M('Paracetamol','500–650 mg every 6–8 h as needed','Up to 3 days','Maximum daily dose/liver review'),M('Cetirizine','5–10 mg at night if allergic symptoms','3–5 days','Sedation'),M('Saline nasal irrigation','As directed','3–5 days','Supportive care')]),
C('uti','Lower UTI (adult woman)','Infectious disease','Primary','Differentiate cystitis from pyelonephritis, pregnancy, male and complicated UTI.',['Fever/flank pain, pregnancy, male patient, sepsis or obstruction → culture/escalate','Avoid fluoroquinolone as routine first-line cystitis'],['Urinalysis','Culture if complicated/recurrent/pregnancy/failure','Pregnancy test where relevant'],['NCDC','ICMR'],[M('Nitrofurantoin','100 mg twice daily','5 days','Not pyelonephritis; renal threshold'),M('Fosfomycin trometamol','3 g single dose','Once','Local susceptibility'),M('Paracetamol','500 mg as needed','1–2 days','Symptom control')]),
C('cap','Community-acquired pneumonia','Infectious disease','Primary / Secondary','Confirm syndrome/severity; use local antibiogram and reassess in 48–72 hours.',['SpO₂ <94%, hypotension, confusion or high work of breathing → hospital','Cultures before antibiotics when severe and feasible'],['Pulse oximetry/respiratory rate','CXR when indicated','CBC/renal; cultures in severe disease'],['NCDC','ICMR'],[M('Amoxicillin','Dose per severity/local guideline','5 days; review stability','Allergy/renal check'),M('Amoxicillin-clavulanate','Dose per severity/local guideline','5–7 days','Selected comorbidity/resistance contexts'),M('Azithromycin','Only atypical/local indication','3–5 days','QT; avoid routine monotherapy')]),
C('typhoid','Enteric (typhoid) fever','Infectious disease','Primary / Secondary','Obtain blood culture before antibiotics where possible; resistance is highly local.',['Shock, encephalopathy, GI bleed/perforation or vomiting → hospital','Avoid empiric fluoroquinolone without susceptibility'],['Blood culture before antibiotics','CBC, LFT, renal','Evaluate malaria/dengue/other fever'],['NCDC','ICMR'],[M('Azithromycin','Weight/severity-appropriate guideline dose','7 days','Uncomplicated; local susceptibility'),M('Ceftriaxone','1–2 g IV once daily','10–14 days','Severe/inpatient; culture-directed'),M('Paracetamol','Within maximum dose','Short course','Hydration/monitoring')]),
C('dengue','Dengue without warning signs','Infectious disease','Primary','Supportive care, fluid plan, trends and daily warning-sign review.',['Pain, persistent vomiting, mucosal bleed, lethargy, fluid accumulation or rising Hct with falling platelets → admit','Avoid aspirin, ibuprofen and IM injections'],['CBC/hematocrit trend','NS1/RT-PCR early or IgM by illness day','Vitals, urine output, warning signs'],['DENGUE','WHO'],[M('Paracetamol','10–15 mg/kg/dose; adult max applies','As needed','No NSAIDs; liver review'),M('Oral rehydration / fluids','Individualized by intake/losses','Frequent reassessment','Avoid overload')]),
C('shock','Severe dengue / dengue shock','Emergency','Hospital only','Time-critical monitored resuscitation; no outpatient prescription is generated.',['Immediate hospital/critical care management','Guideline isotonic crystalloid with frequent reassessment; manage hemorrhage/organ injury'],['Continuous vitals/perfusion/urine','Serial Hct/CBC/metabolic/organ assessment','Cross-match with significant bleeding'],['DENGUE','WHO'],[]),
C('ssti','Cellulitis / soft-tissue infection','Infectious disease','Primary / Secondary','Classify purulent/non-purulent, severity, diabetic foot and necrotizing features.',['Pain out of proportion, crepitus, bullae, shock or rapid spread → surgery emergency','Diabetic foot needs depth/ischemia/osteomyelitis assessment'],['Mark margins/vitals','Culture pus/deep tissue when indicated','Glucose; imaging if deep disease'],['NCDC','ICMR'],[M('Cephalexin','500 mg four times daily','5 days; review','Mild non-purulent; renal/allergy check'),M('Amoxicillin-clavulanate','625 mg three times daily','5–7 days','Selected bite/polymicrobial contexts'),M('Doxycycline','100 mg twice daily','5–7 days','MRSA risk; pregnancy/age cautions')]),
C('diarrhea','Acute infectious diarrhea','Gastrointestinal','Primary','Oral rehydration is central; most watery diarrhea needs no antibiotic.',['Shock, blood with toxicity, severe dehydration or peritonism → urgent care','Avoid antimotility drugs in dysentery/high fever'],['Hydration assessment','Stool testing for selected severe/persistent/outbreak cases'],['ICMR','NCDC'],[M('ORS','Frequent small volumes; replace losses','Until rehydrated','WHO low-osmolarity ORS'),M('Zinc (children)','Age-appropriate dose','10–14 days','Pediatric protocol'),M('Azithromycin','Only selected dysentery/cholera context','Local guidance','Not routine watery diarrhea')]),
C('tinea','Tinea corporis / cruris','Dermatology','Primary','Confirm morphology; avoid steroid-antifungal fixed-dose combinations.',['Scalp/nail, extensive/refractory or immunocompromised → confirm/refer','KOH where uncertain/failure'],['Clinical exam','KOH microscopy if atypical/recurrent'],['ICMR'],[M('Luliconazole 1% cream','Thin layer once daily','1–2 weeks','Continue per guidance'),M('Clotrimazole 1% cream','Thin layer twice daily','2–4 weeks','Keep area dry'),M('Terbinafine 1% cream','Thin layer once/twice daily','1–2 weeks','Avoid steroid combination')]),
C('acne','Acne vulgaris','Dermatology','Primary','Grade severity, pregnancy potential, scarring and psychosocial impact.',['Nodulocystic acne, scarring or distress → dermatology','No topical antibiotic monotherapy; verify pregnancy before retinoid/tetracycline'],['Usually none','Pregnancy assessment when relevant'],['ICMR'],[M('Benzoyl peroxide 2.5%','Thin layer once daily','8–12 weeks','Irritation/bleaching'),M('Adapalene 0.1%','Pea-sized amount at night','8–12 weeks','Avoid pregnancy'),M('Clindamycin 1% + benzoyl peroxide','Once daily','Maximum 12 weeks','Never antibiotic alone'),M('Doxycycline','100 mg once daily','8–12 weeks','Moderate inflammatory; pregnancy/age caution')]),
C('copd','COPD — stable management','Respiratory','Primary / Secondary','Confirm airflow obstruction; technique, smoking cessation, vaccines and rehab are core.',['Acute hypoxia, exhaustion, confusion or silent chest → emergency','Oral steroids/antibiotics only in defined exacerbation pathways'],['Post-bronchodilator spirometry','CAT/mMRC and exacerbations','SpO₂; eosinophils where ICS relevant'],['ICMR','GOLD'],[M('Tiotropium','Device-equivalent once daily','Long term','Technique/device dose'),M('Formoterol/budesonide','Device-appropriate strength','If indicated','ICS by exacerbations/eosinophils/asthma'),M('Levosalbutamol','1–2 puffs as needed','Rescue','Technique/overuse review'),M('Ipratropium/levosalbutamol neb','Device dose','Acute setting only','Reassess/escalate')]),
C('oa','Knee osteoarthritis','Musculoskeletal','Primary','Exercise, weight management and topical therapy precede systemic NSAIDs.',['Hot swollen joint, trauma or inability to bear weight → urgent evaluation','Review GI, renal and CV risk before oral NSAID'],['Clinical diagnosis','Weight-bearing X-ray if uncertain'],['ICMR'],[M('Topical diclofenac','As directed to affected knee','Trial 2–4 weeks','Total NSAID exposure'),M('Paracetamol','Short intermittent use','Review benefit','Maximum daily dose'),M('Oral NSAID','Lowest effective agent/dose','Shortest duration','Only after GI/renal/CV review')]),
C('anxiety','Generalized anxiety symptoms','Mental health','Primary','Confirm diagnosis, impairment, bipolarity, substance and suicide risk; psychotherapy first-line or combined.',['Suicidal intent, psychosis, mania or withdrawal → urgent specialist care','Avoid routine benzodiazepine/etizolam templates'],['GAD-7 / clinical assessment','Targeted labs if indicated'],['ICMR'],[M('Escitalopram','5 mg daily, then 10 mg as tolerated','Review 2–4 weeks','Activation/QT/interactions/taper'),M('Sertraline','25 mg daily, then titrate','Review 2–4 weeks','GI effects/interactions'),M('Non-drug plan','CBT, sleep, activity, substance reduction','Ongoing','Follow-up/safety plan')]),
C('tb','Presumptive / confirmed tuberculosis','National programme','NTEP pathway','Notify/manage through NTEP with confirmation, weight-band regimen, resistance testing and adherence support.',['Hemoptysis, hypoxia, meningitis, spinal deficit or severe illness → urgent referral','No ad-hoc anti-TB combinations'],['NAAT/molecular test','CXR/site evaluation','Baseline safety; HIV/diabetes screening'],['NTEP'],[])
];
const norm=s=>s.toLowerCase().replace(/[^a-z0-9 ]/g,' ');
const rag=q=>{let w=norm(q).split(/\s+/).filter(x=>x.length>2);return CONDITIONS.map(c=>({c,s:w.reduce((n,x)=>n+([c.name,c.group,c.summary,...c.tests,...c.red,...c.meds.flat()].join(' ').toLowerCase().includes(x)?1:0),0)})).filter(x=>x.s).sort((a,b)=>b.s-a.s).map(x=>x.c)};
function App(){const[selected,setSelected]=useState(CONDITIONS[0]),[search,setSearch]=useState(''),[chosen,setChosen]=useState([]),[patient,setPatient]=useState({name:'',age:'',sex:'',weight:'',allergy:'',renal:'',pregnancy:'No / N.A.',notes:''}),[ack,setAck]=useState(false),[tab,setTab]=useState('builder');const matches=useMemo(()=>search?rag(search):CONDITIONS,[search]);const choose=c=>{setSelected(c);setChosen([]);setSearch('');setTab('builder')},add=m=>!chosen.some(x=>x[0]===m[0])&&setChosen([...chosen,[...m]]),update=(i,j,v)=>setChosen(chosen.map((x,k)=>k===i?x.map((y,l)=>l===j?v:y):x));return <div className="app">
<aside><div className="brand"><span><Stethoscope/></span><div><b>India Rx Studio</b><small>Clinical decision support</small></div></div><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Disease, symptom, medicine…"/></div><div className="condition-list">{matches.map(c=><button className={selected.id===c.id?'active':''} onClick={()=>choose(c)} key={c.id}><span>{c.name}<small>{c.group}</small></span><ChevronRight/></button>)}</div><div className="aside-note"><ShieldCheck/><p><b>For registered clinicians</b><br/>Not for self-medication. Verify patient factors, resistance and formulary.</p></div></aside>
<main><header><div><p className="eyebrow">PRIMARY & SECONDARY CARE · INDIA</p><h1>{selected.name}</h1><p>{selected.summary}</p></div><span className="level">{selected.level}</span></header><nav><button className={tab==='builder'?'on':''} onClick={()=>setTab('builder')}><FileText/> Prescription builder</button><button className={tab==='evidence'?'on':''} onClick={()=>setTab('evidence')}><BookOpen/> Evidence</button></nav>
{tab==='builder'?<div className="workspace"><section><div className="card alert"><div className="card-title"><AlertTriangle/> Triage before prescribing</div>{selected.red.map(x=><p key={x}>• {x}</p>)}</div><div className="card"><div className="card-title"><Activity/> Assessment checklist</div><div className="checks">{selected.tests.map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div></div><div className="card"><div className="card-title"><Plus/> Guideline options</div>{selected.meds.length?selected.meds.map(m=><div className="med" key={m[0]}><div><b>{m[0]}</b><span>{m[1]} · {m[2]}</span><small>{m[3]}</small></div><button onClick={()=>add(m)}>Add</button></div>):<div className="no-rx">This condition requires a monitored programme, emergency, or specialist pathway. No routine prescription template is generated.</div>}</div></section>
<section><div className="card"><div className="card-title"><Stethoscope/> Patient & prescription</div><div className="grid">{[['name','Patient name'],['age','Age'],['sex','Sex'],['weight','Weight (kg)'],['allergy','Drug allergies'],['renal','eGFR / renal status'],['pregnancy','Pregnancy'],['notes','Clinical notes / diagnosis']].map(([k,l])=><label key={k}>{l}<input value={patient[k]} onChange={e=>setPatient({...patient,[k]:e.target.value})}/></label>)}</div></div><div className="card rx"><div className="card-title"><FileText/> Selected prescription</div>{!chosen.length?<div className="empty">Add options after clinical review.</div>:chosen.map((m,i)=><div className="rxrow" key={m[0]}><b>{m[0]}</b><input value={m[1]} onChange={e=>update(i,1,e.target.value)}/><input value={m[2]} onChange={e=>update(i,2,e.target.value)}/><button onClick={()=>setChosen(chosen.filter((_,k)=>k!==i))}><Trash2/></button></div>)}<label className="ack"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed diagnosis, allergies, pregnancy, renal/hepatic function, interactions, duplication, contraindications and local guidance.</label><button className="primary" disabled={!ack||!patient.name||!chosen.length} onClick={()=>window.print()}><Printer/> Generate & print prescription</button></div></section></div>:<Evidence selected={selected}/>}</main>
<div className="print-sheet"><h2>Prescription</h2><p><b>Patient:</b> {patient.name} &nbsp; <b>Age:</b> {patient.age} &nbsp; <b>Sex:</b> {patient.sex} &nbsp; <b>Weight:</b> {patient.weight} kg</p><p><b>Diagnosis:</b> {selected.name}</p><p><b>Allergies:</b> {patient.allergy||'Not recorded'} &nbsp; <b>Renal status:</b> {patient.renal||'Not recorded'}</p><ol>{chosen.map(m=><li key={m[0]}><b>{m[0]}</b> — {m[1]} — {m[2]}</li>)}</ol><p><b>Clinical notes:</b> {patient.notes}</p><div className="sign">Prescriber name / registration / signature: ____________________ Date: ________</div><small>Clinician-generated template. Final responsibility remains with the prescribing clinician.</small></div></div>}
function Evidence({selected}){return <div className="evidence"><div className="card"><div className="card-title"><BookOpen/> Retrieved evidence</div><p className="muted">The local retrieval layer maps condition, setting, red flags, assessment and medicine options to sources. It works without an API key.</p>{selected.src.map(id=>{let s=SOURCES.find(x=>x.id===id);return s&&<a className="source" href={s.url} target="_blank" rel="noreferrer" key={id}><div><b>{s.title}</b><span>{s.type} · {s.year}</span></div><ChevronRight/></a>})}</div><div className="card"><div className="card-title"><ShieldCheck/> Evidence governance</div><ul><li>India-first retrieval ranks ICMR, MoHFW, NCDC and national programmes first.</li><li>Antimicrobials require syndrome, severity, allergy, renal function and local antibiogram.</li><li>Seed brand names are normalized to generics and are not endorsements.</li><li>Sources and dates remain visible for clinician verification.</li></ul></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
